{
    'name': 'SustainHub',
    'summary': 'Smart CSR tracking with AI-powered insights and reporting',
    'version': '19.0.0.0.0',
    'category': 'Corporate Social Responsibility',
    'author': 'Abu Dhabi University',
    'license': 'LGPL-3',
    'website': 'https://example.com',
    'images': ['static/description/icon.png'],
    'depends': ['base', 'hr', 'project', 'crm', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'data/demo_data.xml',
        'views/pledge_views.xml',
        'views/progress_views.xml',
        'views/kpi_views.xml',
        'views/dashboard_views.xml',
        'views/report_views.xml',
        'views/project_views_inherit.xml',
        'views/hr_employee_views_inherit.xml',
        'views/crm_views_inherit.xml',
        'views/menu.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'application': True,
}
