from . import pledge
from . import progress
from . import kpi
from . import report
from . import dashboard
from . import project_inherit
from . import project_task_inherit
from . import hr_employee_inherit
from . import crm_inherit
